### ISSUE TITLE
questions re: nordic seas TMI 

### ISSUE THREAD

**Issue by b-r-hamilton** [ggebbie/TMI.jl#121] opened 2023-06-30 21:09 UTC
These may not actually be issues, just questions I have while thinking about the Nordic Seas TMI, specifically the `sourcemap` test. 

- [ ] Should `PO_4true` (boundary conditions, propagated through A), as computed in the `sourcemap` test, be similar to `yPO_4` (just the full PO_4 field from the netcdf)? They are significantly different, and I was wondering if this was expected and what the explanation is for it. Is the `yPO_4` field basically just cleaned-up real-world observations? Does the mismatch between these two variables just demonstrate that the `A` matrix doesn't perfectly solve for the phosphate? 
- [ ] Is the Q^- variable associated with the `u` or `q`? Based on this line https://github.com/ggebbie/TMI.jl/blob/7c6f31a5d7d0cb492ddf7ad45466c1efb676b8c1/src/TMI.jl#L2112 it seems like it's associated with `u`, but calling it `Q` makes it seem like it's associated with `q`. 
- [ ] the output of `sparsedatamap` is the Optim.jl output `out`. At one point, we look at the quantity`out.minimum` - Optim.jl says this is the "minimum of the objective function", is this different from the cost function? It has a different value than `$\tilde{J}` as far as I know
- [ ] what's the logic behind providing `uvec` and `$u_0$` as arguments to `costfunction_point_obs!` and `sparsedatamap`? In `costfunction_point_obs!`, an `unvec` is immediately performed, so I'm not sure why, uvec is required. Is there some logic somewhere where one variable is being modified but not the other? 
- [ ] more of a stylistic code thing: in `costfunction_point_obs!` there's a conditional where `guvec != nothing`. Would it make more sense for `guvec` to just be an optional argument? 
- [ ] all of the functions that are `g[some other function]` (e.g. `gobserve`, 'gsteadyinversion`) - are these just the version that is propagating a gradient? What's the basic difference between these and their original version? (these functions are all used in `sparsedatamap`, I think I just don't quite understand what's happening in this function.

**Comment by ggebbie** [comment] 2023-07-03 14:43
1. `PO_4true` and `yPO_4`: I find that the two are basically the same (10^-14 difference) except on the north-surface intersection strip. This strip has boundary conditions applied twice, but it should only happen once. Numerically, there is no impact on the interior ocean. 

2. The cost function has a term u^T Q^-1 u. This is a clash between control theory and biogeochemical notation. 

3. objective function = cost function

4. uvec is required by Optim.jl unfortunately. The structure of u_0 is currently needed to properly unpack/pack the vector. There are ways around this but this information will need to be passed to the cost function somehow. 

5. Stylistically this is a good idea. The issue is satisfying the requirements of Optim.jl. I was unable to reconcile both constraints but it might be possible.

6. Yes, `g` functions are used to calculate gradients. They are the adjoint functions of the forward functions which do not have an extra `g` at the front. These functions have been hand-coded following the recipes in books like Griewank and Walther 1995. Enzyme.jl appears to be the preferred way to try to generate them automatically but I have not tried it for these cases yet. The gradients could also profitably included as part of the original Field and BoundaryCondition structs. Another approach would be to use Dual Numbers.

**Comment by b-r-hamilton** [comment] 2023-07-03 18:06
1. I double-checked, I think they are different at all surface - edge boundaries: is this still expected? I made a quick plot comparing the elementwise differences between the two for the surface layer. 
![image](https://github.com/ggebbie/TMI.jl/assets/57123440/7d2a7d91-8d63-4afa-945f-18d718e35101)
2.
3. I double-checked `\tilde{J}` and it does have the same value as `out.minimum`. I think I had run something in the wrong order originally. 

the rest of this all makes sense! thanks for clarifying.

**Comment by ggebbie** [comment] 2023-07-03 18:14
1. It does make sense for all lateral-surface boundary condition intersections to have a problem. UnicodePlots made it appear like only the north-surface intersection had an issue. This must be an artifact of using `heatmap` instead of `contourf`.  None of these points affect the interior, but it should still be fixed nonetheless. One solution is to define the lateral boundaries after the surface boundary has been defined, and then to check that the boundaries are not doubly-defined.

**Comment by ggebbie** [comment] 2023-11-15 21:06
I will close this discussion. The outstanding work item is in #106

**Closed by ggebbie** 2023-11-15 21:06 UTC
